/**
 * Email Sender Module
 * ===================
 * Sends HTML email digests with shortlisted job postings.
 * Uses nodemailer with SMTP (Gmail-compatible).
 *
 * NOTE: For Gmail, the user needs to set up an App Password
 * (https://myaccount.google.com/apppasswords) and store it in SMTP_PASS env var.
 */

import nodemailer from "nodemailer";

export interface EmailJobEntry {
  title: string;
  company: string;
  location: string;
  url: string;
  matchScore: number;
  rationale: string;
  cvVariant: string;
  source: string;
}

export interface SendDigestParams {
  recipient: string;
  jobs: EmailJobEntry[];
  recipientName?: string;
}

const getTransporter = () => {
  const user = process.env.SMTP_USER || "";
  const pass = process.env.SMTP_PASS || "";

  if (!pass) {
    const err = new Error(
      "SMTP_PASS environment variable is not set. To enable email alerts, set up a Gmail App Password at https://myaccount.google.com/apppasswords and set SMTP_PASS (and SMTP_USER for the sender email) in your Vercel environment variables."
    );
    (err as any).code = "SMTP_NOT_CONFIGURED";
    throw err;
  }

  return nodemailer.createTransport({
    host: process.env.SMTP_HOST || "smtp.gmail.com",
    port: parseInt(process.env.SMTP_PORT || "465"),
    secure: true,
    auth: { user, pass },
  });
};

const buildEmailHtml = (jobs: EmailJobEntry[], recipientName: string): string => {
  // Group jobs by CV variant
  const grouped: Record<string, EmailJobEntry[]> = {};
  for (const job of jobs) {
    if (!grouped[job.cvVariant]) grouped[job.cvVariant] = [];
    grouped[job.cvVariant].push(job);
  }

  // Sort each group by match score descending
  for (const variant of Object.keys(grouped)) {
    grouped[variant].sort((a, b) => b.matchScore - a.matchScore);
  }

  const sections = Object.entries(grouped)
    .map(([variant, jobs]) => {
      const jobCards = jobs
        .map(
          (job) => `
        <tr>
          <td style="padding:16px;border-bottom:1px solid #e5e7eb;">
            <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px;">
              <div>
                <div style="font-size:16px;font-weight:600;color:#1b365d;">${escapeHtml(job.title)}</div>
                <div style="font-size:13px;color:#606774;margin-top:2px;">${escapeHtml(job.company)} · ${escapeHtml(job.location)} · <span style="text-transform:uppercase;font-size:11px;color:#8c7853;">${escapeHtml(job.source)}</span></div>
              </div>
              <div style="font-size:18px;font-weight:700;color:${job.matchScore >= 80 ? "#16a34a" : job.matchScore >= 60 ? "#d97706" : "#6b7280"};min-width:50px;text-align:right;">${job.matchScore}%</div>
            </div>
            <div style="font-size:13px;color:#374151;line-height:1.5;margin-top:8px;">${escapeHtml(job.rationale)}</div>
            <a href="${escapeHtml(job.url)}" target="_blank" rel="noopener noreferrer" style="display:inline-block;margin-top:10px;padding:6px 14px;background:#1b365d;color:#fff;text-decoration:none;border-radius:4px;font-size:13px;font-weight:500;">View Job →</a>
          </td>
        </tr>`
        )
        .join("");

      return `
        <div style="margin-bottom:32px;">
          <h2 style="font-size:14px;font-weight:700;color:#8c7853;text-transform:uppercase;letter-spacing:0.05em;margin:0 0 12px 0;padding-bottom:8px;border-bottom:2px solid #8c7853;">${escapeHtml(variant)} · ${jobs.length} jobs</h2>
          <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">${jobCards}</table>
        </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;">
  <div style="max-width:680px;margin:0 auto;padding:24px 16px;">
    <div style="background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.08);">
      <div style="background:#1b365d;padding:24px 32px;">
        <h1 style="margin:0;font-size:22px;color:#fff;font-weight:600;">Your Job Match Digest</h1>
        <p style="margin:4px 0 0 0;font-size:13px;color:#cbd5e0;">${jobs.length} shortlisted opportunities for ${escapeHtml(recipientName)}</p>
      </div>
      <div style="padding:24px 32px;">
        ${sections}
      </div>
      <div style="padding:16px 32px;background:#f9fafb;border-top:1px solid #e5e7eb;">
        <p style="margin:0;font-size:12px;color:#6b7280;">Generated by your CV Tailor & Job Hunter platform · ${new Date().toLocaleString()}</p>
      </div>
    </div>
  </div>
</body></html>`;
};

const escapeHtml = (s: string): string =>
  s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

export const sendJobDigestEmail = async (params: SendDigestParams): Promise<{ success: boolean; messageId?: string; error?: string }> => {
  if (!params.jobs.length) {
    return { success: false, error: "No jobs to send" };
  }

  try {
    const transporter = getTransporter();
    const recipientName = params.recipientName || params.recipient.split("@")[0];
    const html = buildEmailHtml(params.jobs, recipientName);
    const subject = `Your Job Match Digest — ${params.jobs.length} opportunities found`;

    const info = await transporter.sendMail({
      from: `"CV Platform" <${process.env.SMTP_USER}>`,
      to: params.recipient,
      subject,
      html,
    });

    return { success: true, messageId: info.messageId };
  } catch (err: any) {
    return { success: false, error: err.message || String(err) };
  }
};
